# Generated by Django 5.2.12 on 2026-03-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_staff_systemsettings_attendance_sign_out_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sign_out_time',
        ),
    ]
