# Generated by Django 5.2.12 on 2026-03-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_sign_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='image',
            field=models.ImageField(upload_to='training_images/'),
        ),
    ]
